---
- name: restart RoboZonky
  systemd: name=robozonky state=restarted enabled=true daemon_reload=yes
- name: Log in
  shell: 'touch {{robozonky_data_path}}/must-log-in && (echo | "{{robozonky_path}}/robozonky-cli" "@{{robozonky_data_path}}/robozonky-login.cli" ) && rm {{robozonky_data_path}}/must-log-in'
  become_user: "{{robozonky_user_name}}"
  notify: restart RoboZonky
