---
- name: restart RoboZonky
  systemd: name=robozonky state=restarted enabled=true daemon_reload=yes
- name: Log in
  shell: '"{{robozonky_path}}/robozonky-login-by-code"'
  become_user: "{{robozonky_user_name}}"
  notify: restart RoboZonky
